// ─── Word Categories ──────────────────────────────────────────────────────────
pub const Category = enum {
    common,
    programming,
    numbers,
    quotes,
    punctuation,
};

pub fn categoryLabel(cat: Category) []const u8 {
    return switch (cat) {
        .common => "Common Words",
        .programming => "Programming",
        .numbers => "Numbers",
        .quotes => "Famous Quotes",
        .punctuation => "Punctuation",
    };
}

pub const ALL_CATEGORIES = [_]Category{ .common, .programming, .numbers, .quotes, .punctuation };

// ─── 500 most common English words ──────────────────────────────────────────
pub const common_words = [_][]const u8{
    // 1-50
    "the",      "be",        "to",       "of",          "and",
    "a",        "in",        "that",     "have",        "it",
    "for",      "not",       "on",       "with",        "he",
    "as",       "you",       "do",       "at",          "this",
    "but",      "his",       "by",       "from",        "they",
    "we",       "say",       "her",      "she",         "or",
    "an",       "my",        "will",     "one",         "all",
    "would",    "there",     "their",    "what",        "so",
    "up",       "out",       "if",       "about",       "who",
    "get",      "which",     "go",       "me",          "when",
    // 51-100
    "make",     "can",       "like",     "time",        "no",
    "just",     "him",       "know",     "take",        "people",
    "into",     "year",      "your",     "good",        "some",
    "could",    "them",      "see",      "other",       "than",
    "then",     "now",       "look",     "only",        "come",
    "its",      "over",      "think",    "also",        "back",
    "after",    "use",       "two",      "how",         "our",
    "work",     "first",     "well",     "way",         "even",
    "new",      "want",      "because",  "any",         "these",
    "give",     "day",       "most",     "us",          "great",
    // 101-150
    "between",  "need",      "large",    "often",       "hand",
    "high",     "place",     "hold",     "turn",        "move",
    "live",     "feel",      "fact",     "change",      "off",
    "play",     "small",     "number",   "always",      "next",
    "open",     "seem",      "together", "white",       "children",
    "begin",    "got",       "walk",     "example",     "ease",
    "paper",    "group",     "music",    "those",       "both",
    "mark",     "book",      "letter",   "until",       "mile",
    "river",    "car",       "feet",     "care",        "second",
    "enough",   "plain",     "girl",     "usual",       "young",
    "ready",    "above",     "ever",     "red",         "list",
    "though",   "feel",      "talk",     "bird",        "soon",
    "body",     "dog",       "family",   "direct",      "leave",
    "song",     "measure",   "door",     "product",     "black",
    "short",    "class",     "wind",     "question",    "happen",
    "complete", "ship",      "area",     "half",        "rock",
    "order",    "fire",      "south",    "problem",     "piece",
    "told",     "knew",      "pass",     "since",       "top",
    "whole",    "king",      "space",    "heard",       "best",
    "hour",     "better",    "true",     "during",      "hundred",
    "five",     "remember",  "step",     "early",       "west",
    "ground",   "interest",  "reach",    "fast",        "verb",
    "sing",     "listen",    "six",      "table",       "travel",
    "less",     "morning",   "ten",      "simple",      "several",
    "vowel",    "toward",    "war",      "lay",         "against",
    "pattern",  "slow",      "center",   "love",        "person",
    "money",    "serve",     "appear",   "road",        "map",
    "rain",     "rule",      "govern",   "pull",        "cold",
    "notice",   "voice",     "unit",     "power",       "town",
    "fine",     "drive",     "lead",     "cry",         "dark",
    "machine",  "note",      "wait",     "plan",        "figure",
    "star",     "box",       "noun",     "field",       "rest",
    "correct",  "able",      "pound",    "done",        "beauty",
    "stood",    "contain",   "front",    "teach",       "week",
    "final",    "gave",      "green",    "oh",          "quick",
    "develop",  "ocean",     "warm",     "free",        "minute",
    "strong",   "special",   "mind",     "behind",      "clear",
    "tail",     "produce",   "fact",     "street",      "inch",
    "multiply", "nothing",   "course",   "stay",        "wheel",
    "full",     "force",     "blue",     "object",      "decide",
    "surface",  "deep",      "moon",     "island",      "foot",
    "system",   "busy",      "test",     "record",      "boat",
    "common",   "gold",      "possible", "plane",       "stead",
    "dry",      "wonder",    "laugh",    "thousand",    "ago",
    "ran",      "check",     "game",     "shape",       "equate",
    "hot",      "miss",      "brought",  "heat",        "snow",
    "tire",     "bring",     "yes",      "distant",     "fill",
    "east",     "paint",     "language", "among",       "grand",
    "ball",     "yet",       "wave",     "drop",        "heart",
    "am",       "present",   "heavy",    "dance",       "engine",
    "position", "arm",       "wide",     "sail",        "material",
    "size",     "vary",      "settle",   "speak",       "weight",
    "general",  "ice",       "matter",   "circle",      "pair",
    "include",  "divide",    "syllable", "felt",        "perhaps",
    "pick",     "sudden",    "count",    "square",      "reason",
    "length",   "represent", "art",      "subject",     "region",
    "energy",   "hunt",      "probable", "bed",         "brother",
    "egg",      "ride",      "cell",     "believe",     "fraction",
    "forest",   "sit",       "race",     "window",      "store",
    "summer",   "train",     "sleep",    "prove",       "lone",
    "leg",      "exercise",  "wall",     "catch",       "mount",
    "wish",     "sky",       "board",    "joy",         "winter",
    "sat",      "written",   "wild",     "instrument",  "kept",
    "glass",    "grass",     "cow",      "job",         "edge",
    "sign",     "visit",     "past",     "soft",        "fun",
    "bright",   "gas",       "weather",  "month",       "million",
    "bear",     "finish",    "happy",    "hope",        "flower",
    "clothe",   "strange",   "gone",     "jump",        "baby",
    "eight",    "village",   "meet",     "root",        "buy",
    "raise",    "solve",     "metal",    "whether",     "push",
    "seven",    "paragraph", "third",    "shall",       "held",
    "hair",     "describe",  "cook",     "floor",       "either",
    "result",   "burn",      "hill",     "safe",        "cat",
    "century",  "consider",  "type",     "law",         "bit",
    "coast",    "copy",      "phrase",   "silent",      "tall",
    "sand",     "soil",      "roll",     "temperature", "finger",
    "industry", "value",     "fight",    "lie",         "beat",
    "excite",   "natural",   "view",     "sense",       "ear",
    "else",     "quite",     "broke",
};

// ─── Programming keywords ───────────────────────────────────────────────────
pub const programming_words = [_][]const u8{
    "function",   "return",  "const",      "let",      "var",       "if",          "else",      "for",           "while",
    "switch",     "case",    "break",      "continue", "try",       "catch",       "throw",     "finally",       "class",
    "interface",  "extends", "implements", "public",   "private",   "protected",   "static",    "void",          "null",
    "undefined",  "true",    "false",      "async",    "await",     "import",      "export",    "default",       "from",
    "as",         "type",    "enum",       "struct",   "package",   "module",      "namespace", "using",         "new",
    "delete",     "this",    "super",      "self",     "prototype", "constructor", "get",       "set",           "yield",
    "static",     "final",   "abstract",   "override", "virtual",   "inline",      "extern",    "sizeof",        "typeof",
    "instanceof", "in",      "of",         "not",      "and",       "or",          "is",        "nil",           "none",
    "lambda",     "def",     "print",      "echo",     "puts",      "printf",      "format",    "len",           "range",
    "map",        "filter",  "reduce",     "foreach",  "array",     "list",        "dict",      "set",           "tuple",
    "object",     "string",  "number",     "boolean",  "integer",   "float",       "double",    "char",          "byte",
    "bool",       "long",    "short",      "unsigned", "signed",    "const",       "pointer",   "reference",     "alloc",
    "free",       "malloc",  "calloc",     "realloc",  "memcpy",    "memset",      "strlen",    "strcpy",        "strcmp",
    "strcat",     "printf",  "scanf",      "sprintf",  "fopen",     "fclose",      "fread",     "fwrite",        "malloc",
    "panic",      "error",   "debug",      "trace",    "log",       "info",        "warn",      "fatal",         "panic",
    "assert",     "require", "include",    "define",   "ifdef",     "endif",       "pragma",    "inline",        "register",
    "volatile",   "mutable", "explicit",   "friend",   "operator",  "template",    "typename",  "concept",       "requires",
    "move",       "copy",    "swap",       "forward",  "decltype",  "auto",        "constexpr", "static_assert", "noexcept",
    "override",   "final",   "virtual",    "pure",
};

// ─── Numbers (for numeric typing practice) ──────────────────────────────────
pub const number_words = [_][]const u8{
    "one",         "two",          "three",      "four",       "five",        "six",        "seven",      "eight",       "nine",         "ten",
    "eleven",      "twelve",       "thirteen",   "fourteen",   "fifteen",     "sixteen",    "seventeen",  "eighteen",    "nineteen",     "twenty",
    "thirty",      "forty",        "fifty",      "sixty",      "seventy",     "eighty",     "ninety",     "hundred",     "thousand",     "million",
    "billion",     "zero",         "twenty-one", "thirty-two", "forty-three", "fifty-four", "sixty-five", "seventy-six", "eighty-seven", "ninety-eight",
    "one-hundred", "one-thousand", "123",        "456",        "789",         "321",        "654",        "987",         "111",          "222",
    "333",         "444",          "555",        "666",        "777",         "888",        "999",        "000",         "101",          "202",
    "303",         "404",          "505",        "606",        "707",         "808",        "909",        "121",         "232",          "343",
    "454",         "565",          "676",        "787",        "898",         "909",        "135",        "246",         "357",          "468",
    "579",         "680",          "791",        "802",        "913",         "024",        "159",        "357",         "951",          "753",
    "486",         "294",          "3.14",       "2.71",       "1.41",        "1.73",       "9.81",       "6.28",        "1.62",         "2.00",
    "5.00",        "0.5",          "0.25",       "0.75",       "0.1",         "0.01",       "0.001",      "100",         "200",          "300",
    "400",         "500",          "600",        "700",        "800",         "900",        "1000",       "2000",        "5000",         "10000",
};

// ─── Famous quotes (for quote typing practice) ───────────────────────────────
pub const quote_words = [_][]const u8{
    "the",       "only",           "way",         "to",      "do",          "great",   "work",        "is",        "to",       "love",
    "what",      "you",            "stay",        "hungry",  "stay",        "foolish", "think",       "different", "innovate", "life",
    "is",        "what",           "happens",     "when",    "you",         "are",     "busy",        "making",    "other",    "plans",
    "the",       "future",         "belongs",     "to",      "those",       "who",     "believe",     "in",        "the",      "beauty",
    "of",        "their",          "dreams",      "success", "is",          "not",     "final",       "failure",   "is",       "not",
    "fatal",     "it",             "is",          "the",     "courage",     "to",      "continue",    "that",      "counts",   "believe",
    "you",       "can",            "and",         "you",     "are",         "halfway", "there",       "the",       "best",     "time",
    "to",        "plant",          "a",           "tree",    "was",         "twenty",  "years",       "ago",       "the",      "second",
    "best",      "time",           "is",          "now",     "it",          "does",    "not",         "matter",    "how",      "slowly",
    "you",       "go",             "as",          "long",    "as",          "you",     "do",          "not",       "stop",     "everything",
    "has",       "beauty",         "but",         "not",     "everyone",    "sees",    "it",          "happiness", "is",       "not",
    "something", "ready",          "made",        "it",      "comes",       "from",    "your",        "own",       "actions",  "the",
    "only",      "impossible",     "journey",     "is",      "the",         "one",     "you",         "never",     "start",    "start",
    "where",     "you",            "are",         "use",     "what",        "you",     "have",        "do",        "what",     "you",
    "can",       "be",             "the",         "change",  "you",         "wish",    "to",          "see",       "in",       "the",
    "world",     "knowledge",      "is",          "power",   "information", "is",      "liberating",  "education", "is",       "the",
    "passport",  "to",             "the",         "future",  "dream",       "big",     "work",        "hard",      "stay",     "humble",
    "actions",   "speak",          "louder",      "than",    "words",       "aim",     "for",         "the",       "moon",     "even",
    "if",        "you",            "miss",        "you",     "will",        "land",    "among",       "the",       "stars",    "every",
    "moment",    "is",             "a",           "fresh",   "beginning",   "never",   "give",        "up",        "on",       "your",
    "dreams",    "passion",        "is",          "the",     "key",         "to",      "success",     "create",    "your",     "own",
    "sunshine",  "choose",         "joy",         "make",    "today",       "amazing", "stars",       "cannot",    "shine",    "without",
    "darkness",  "transformation", "is",          "not",     "changing",    "who",     "you",         "are",       "but",      "becoming",
    "who",       "you",            "could",       "be",      "one",         "small",   "step",        "for",       "man",      "one",
    "giant",     "leap",           "for",         "mankind", "code",        "is",      "like",        "humor",     "when",     "you",
    "have",      "to",             "explain",     "it",      "it",          "is",      "bad",         "first",     "solve",    "the",
    "problem",   "then",           "write",       "the",     "code",        "any",     "fool",        "can",       "write",    "code",
    "that",      "a",              "computer",    "can",     "understand",  "good",    "programmers", "write",     "code",     "humans",
    "can",       "understand",     "programming", "is",      "the",         "art",     "of",          "telling",   "another",  "human",
    "what",      "you",            "want",        "the",     "computer",    "to",      "do",
};

// ─── Punctuation (capitals, commas, semicolons, full sentences) ──────────────
pub const punctuation_words = [_][]const u8{
    "Hello,",     "world!",     "How",        "are",        "you?",       "I'm",        "fine,",      "thanks.",
    "Wait;",      "stop.",      "Yes,",       "no,",        "maybe.",     "It's",       "a",          "test:",
    "one,",       "two,",       "three.",     "Don't",      "panic!",     "Really?",    "Sure.",      "Well,",
    "then;",      "let's",      "go.",        "First,",     "second;",    "third.",     "Code,",      "test,",
    "ship!",      "Up,",        "down,",      "left,",      "right.",     "Now;",       "later.",     "Quick!",
    "Slow...",    "Maybe?",     "Always.",    "Never,",     "ever.",      "Read;",      "write;",     "run.",
    "Save,",      "load,",      "exit.",      "Push;",      "pull;",      "merge.",     "True,",      "false;",
    "null.",      "Add,",       "sub,",       "mul,",       "div.",       "if,",        "else;",      "while.",
    "Hi!",        "Bye.",       "Wow!",       "Hmm...",     "OK;",        "done.",      "Stop!",      "Wait...",
    "Why?",       "Because.",   "Who?",       "What?",      "When?",      "Where?",     "How?",       "Fast,",
    "faster;",    "fastest!",   "Type,",      "type;",      "type.",      "Begin;",     "pause;",     "end.",
    "(yes)",      "[no]",       "{ok}",       "'quote'",    "a-b-c",      "x/y",        "1+1=2;",     "3*3=9.",
    "He",         "said:",      "\"go!\"",    "She",        "asked:",     "\"why?\"",   "Mr.",        "Smith,",
    "Dr.",        "Jones;",     "etc.",       "e.g.",       "i.e.,",      "vs.",        "p.s.",       "a.m.",
    "p.m.;",      "100%",       "50/50",      "yes/no",     "on;",        "off.",       "top,",       "bottom;",
    "live,",      "laugh,",     "love.",      "win;",       "lose;",      "draw.",
};

// ─── Get word list by category ───────────────────────────────────────────────
pub fn getWordList(cat: Category) []const []const u8 {
    return switch (cat) {
        .common => &common_words,
        .programming => &programming_words,
        .numbers => &number_words,
        .quotes => &quote_words,
        .punctuation => &punctuation_words,
    };
}

// Legacy accessor
pub const word_list = common_words;
