// ─── 500 most common English words ──────────────────────────────────────────
pub const word_list = [_][]const u8{
    // 1-50
    "the",         "be",       "to",       "of",        "and",
    "a",           "in",       "that",     "have",      "it",
    "for",         "not",      "on",       "with",      "he",
    "as",          "you",      "do",       "at",        "this",
    "but",         "his",      "by",       "from",      "they",
    "we",          "say",      "her",      "she",       "or",
    "an",          "will",     "my",       "one",       "all",
    "would",       "there",    "their",    "what",      "so",
    "up",          "out",      "if",       "about",     "who",
    "get",         "which",    "go",       "me",        "when",
    // 51-100
    "make",        "can",      "like",     "time",      "no",
    "just",        "him",      "know",     "take",      "people",
    "into",        "year",     "your",     "good",      "some",
    "could",       "them",     "see",      "other",     "than",
    "then",        "now",      "look",     "only",      "come",
    "its",         "over",     "think",    "also",      "back",
    "after",       "use",      "two",      "how",       "our",
    "work",        "first",    "well",     "way",       "even",
    "new",         "want",     "because",  "any",       "these",
    "give",        "day",      "most",     "us",        "great",
    // 101-150
    "between",     "need",     "large",    "often",     "hand",
    "high",        "place",    "hold",     "turn",      "move",
    "live",        "feel",     "fact",     "change",    "off",
    "play",        "small",    "number",   "off",       "always",
    "next",        "open",     "seem",     "together",  "next",
    "white",       "children", "begin",    "got",       "walk",
    "example",     "ease",     "paper",    "group",     "always",
    "music",       "those",    "both",     "mark",      "book",
    "letter",      "until",    "mile",     "river",     "car",
    "feet",        "care",     "second",   "enough",    "plain",
    // 151-200
    "girl",        "usual",    "young",    "ready",     "above",
    "ever",        "red",      "list",     "though",    "feel",
    "talk",        "bird",     "soon",     "body",      "dog",
    "family",      "direct",   "pose",     "leave",     "song",
    "measure",     "door",     "product",  "black",     "short",
    "numeral",     "class",    "wind",     "question",  "happen",
    "complete",    "ship",     "area",     "half",      "rock",
    "order",       "fire",     "south",    "problem",   "piece",
    "told",        "knew",     "pass",     "since",     "top",
    "whole",       "king",     "space",    "heard",     "best",
    // 201-250
    "hour",        "better",   "true",     "during",    "hundred",
    "five",        "remember", "step",     "early",     "hold",
    "west",        "ground",   "interest", "reach",     "fast",
    "verb",        "sing",     "listen",   "six",       "table",
    "travel",      "less",     "morning",  "ten",       "simple",
    "several",     "vowel",    "toward",   "war",       "lay",
    "against",     "pattern",  "slow",     "center",    "love",
    "person",      "money",    "serve",    "appear",    "road",
    "map",         "rain",     "rule",     "govern",    "pull",
    "cold",        "notice",   "voice",    "unit",      "power",
    // 251-300
    "town",        "fine",     "drive",    "lead",      "cry",
    "dark",        "machine",  "note",     "wait",      "plan",
    "figure",      "star",     "box",      "noun",      "field",
    "rest",        "correct",  "able",     "pound",     "done",
    "beauty",      "drive",    "stood",    "contain",   "front",
    "teach",       "week",     "final",    "gave",      "green",
    "oh",          "quick",    "develop",  "ocean",     "warm",
    "free",        "minute",   "strong",   "special",   "mind",
    "behind",      "clear",    "tail",     "produce",   "fact",
    "street",      "inch",     "multiply", "nothing",   "course",
    // 301-350
    "stay",        "wheel",    "full",     "force",     "blue",
    "object",      "decide",   "surface",  "deep",      "moon",
    "island",      "foot",     "system",   "busy",      "test",
    "record",      "boat",     "common",   "gold",      "possible",
    "plane",       "stead",    "dry",      "wonder",    "laugh",
    "thousand",    "ago",      "ran",      "check",     "game",
    "shape",       "equate",   "hot",      "miss",      "brought",
    "heat",        "snow",     "tire",     "bring",     "yes",
    "distant",     "fill",     "east",     "paint",     "language",
    "among",       "grand",    "ball",     "yet",       "wave",
    // 351-400
    "drop",        "heart",    "am",       "present",   "heavy",
    "dance",       "engine",   "position", "arm",       "wide",
    "sail",        "material", "size",     "vary",      "settle",
    "speak",       "weight",   "general",  "ice",       "matter",
    "circle",      "pair",     "include",  "divide",    "syllable",
    "felt",        "perhaps",  "pick",     "sudden",    "count",
    "square",      "reason",   "length",   "represent", "art",
    "subject",     "region",   "energy",   "hunt",      "probable",
    "bed",         "brother",  "egg",      "ride",      "cell",
    "believe",     "fraction", "forest",   "sit",       "race",
    // 401-450
    "window",      "store",    "summer",   "train",     "sleep",
    "prove",       "lone",     "leg",      "exercise",  "wall",
    "catch",       "mount",    "wish",     "sky",       "board",
    "joy",         "winter",   "sat",      "written",   "wild",
    "instrument",  "kept",     "glass",    "grass",     "cow",
    "job",         "edge",     "sign",     "visit",     "past",
    "soft",        "fun",      "bright",   "gas",       "weather",
    "month",       "million",  "bear",     "finish",    "happy",
    "hope",        "flower",   "clothe",   "strange",   "gone",
    "jump",        "baby",     "eight",    "village",   "meet",
    // 451-500
    "root",        "buy",      "raise",    "solve",     "metal",
    "whether",     "push",     "seven",    "paragraph", "third",
    "shall",       "held",     "hair",     "describe",  "cook",
    "floor",       "either",   "result",   "burn",      "hill",
    "safe",        "cat",      "century",  "consider",  "type",
    "law",         "bit",      "coast",    "copy",      "phrase",
    "silent",      "tall",     "sand",     "soil",      "roll",
    "temperature", "finger",   "industry", "value",     "fight",
    "lie",         "beat",     "excite",   "natural",   "view",
    "sense",       "ear",      "else",     "quite",     "broke",
};
